<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="28" failures="4" skipped="2">
	<testsuite name="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" tests="28" failures="4" errors="0" id="0" hostname="thiago-lugli-ubuntu" skipped="2" time="57.085" timestamp="2023-08-17T16:33:53-03:00">
		<testcase name="TestCreateProjectSuccess" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.030"></testcase>
		<testcase name="TestCreateProjectSuccess/Test_create_project_success_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.020"></testcase>
		<testcase name="TestCreateProjectSuccess/Test_create_project_success_index:_1" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.010"></testcase>
		<testcase name="TestCreateProjectFail" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.010"></testcase>
		<testcase name="TestCreateProjectFail/Test_create_project_fail_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.010"></testcase>
		<testcase name="TestDeployProjectSuccess" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.000"></testcase>
		<testcase name="TestQuarkusBuildCommand" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="24.500">
			<failure message="Failed"></failure>
		</testcase>
		<testcase name="TestQuarkusBuildCommand/Test_build_project_success_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="16.370">
			<failure message="Failed"><![CDATA[    quarkus_build_test.go:124: 
        	Error Trace:	/home/thiago-lugli/ibm/kie-tools/packages/kn-plugin-workflow/it-tests/quarkus_build_test.go:124
        	            				/home/thiago-lugli/ibm/kie-tools/packages/kn-plugin-workflow/it-tests/quarkus_build_test.go:107
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestQuarkusBuildCommand/Test_build_project_success_index:_0
        	Messages:   	Expected nil error, got exit status 1]]></failure>
		</testcase>
		<testcase name="TestQuarkusBuildCommand/Test_build_project_success_index:_1" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="3.890">
			<failure message="Failed"><![CDATA[    quarkus_build_test.go:124: 
        	Error Trace:	/home/thiago-lugli/ibm/kie-tools/packages/kn-plugin-workflow/it-tests/quarkus_build_test.go:124
        	            				/home/thiago-lugli/ibm/kie-tools/packages/kn-plugin-workflow/it-tests/quarkus_build_test.go:107
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestQuarkusBuildCommand/Test_build_project_success_index:_1
        	Messages:   	Expected nil error, got exit status 1]]></failure>
		</testcase>
		<testcase name="TestQuarkusBuildCommand/Test_build_project_success_index:_2" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="4.230">
			<failure message="Failed"><![CDATA[    quarkus_build_test.go:124: 
        	Error Trace:	/home/thiago-lugli/ibm/kie-tools/packages/kn-plugin-workflow/it-tests/quarkus_build_test.go:124
        	            				/home/thiago-lugli/ibm/kie-tools/packages/kn-plugin-workflow/it-tests/quarkus_build_test.go:107
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestQuarkusBuildCommand/Test_build_project_success_index:_2
        	Messages:   	Expected nil error, got exit status 1]]></failure>
		</testcase>
		<testcase name="TestQuarkusConvertProjectSuccess" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="17.320"></testcase>
		<testcase name="TestQuarkusConvertProjectSuccess/Test_quarkus_convert_project_success_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="4.550"></testcase>
		<testcase name="TestQuarkusConvertProjectSuccess/Test_quarkus_convert_project_success_index:_1" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.570"></testcase>
		<testcase name="TestQuarkusConvertProjectSuccess/Test_quarkus_convert_project_success_index:_2" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="10.210"></testcase>
		<testcase name="TestQuarkusConvertProjectFailed" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.020"></testcase>
		<testcase name="TestQuarkusConvertProjectFailed/Test_quarkus_convert_project_fail_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.020"></testcase>
		<testcase name="TestQuarkusConvertProjectFailedAlreadyQuarkus" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.180"></testcase>
		<testcase name="TestQuarkusConvertProjectFailedAlreadyQuarkus/Test_quarkus_convert_project_fail_already_quarkus_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.180"></testcase>
		<testcase name="TestQuarkusCreateProjectSuccess" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="8.810"></testcase>
		<testcase name="TestQuarkusCreateProjectSuccess/Test_quarkus_create_project_success_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.320"></testcase>
		<testcase name="TestQuarkusCreateProjectSuccess/Test_quarkus_create_project_success_index:_1" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.110"></testcase>
		<testcase name="TestQuarkusCreateProjectSuccess/Test_quarkus_create_project_success_index:_2" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="1.960"></testcase>
		<testcase name="TestQuarkusCreateProjectSuccess/Test_quarkus_create_project_success_index:_3" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.410"></testcase>
		<testcase name="TestQuarkusCreateProjectFail" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="2.200"></testcase>
		<testcase name="TestQuarkusCreateProjectFail/Test_quarkus_create_project_fail_index:_0" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.310"></testcase>
		<testcase name="TestQuarkusCreateProjectFail/Test_quarkus_create_project_fail_index:_1" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="1.880"></testcase>
		<testcase name="TestQuarkusRunCommand" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.000">
			<skipped message="Skipped"><![CDATA[    quarkus_run_test.go:77: Skipping test because of `quarkus run` not working properly. Probably related to https://issues.redhat.com/browse/KOGITO-9449]]></skipped>
		</testcase>
		<testcase name="TestRunCommand" classname="github.com/kiegroup/kie-tools/packages/kn-plugin-workflow/it-tests" time="0.000">
			<skipped message="Skipped"><![CDATA[    run_test.go:71: Skipping test because of `run` not working properly on osx]]></skipped>
		</testcase>
	</testsuite>
</testsuites>
